org: tsmarsh
app: dementor
service: dementor

frameworkVersion: '3'

provider:
  name: aws
  runtime: java17
  tracing:
    apiGateway: true
    lambda: true

package:
  artifact: target/dementor-beta.jar

functions:
  webhook:
    handler: com.tailoredshapes.dementor.aws.WebhookHandler


plugins:
  - serverless-offline
  - serverless-secrets-plugin
  - serverless-scriptable-plugin
